// Syncs lib/src/sdk_version.dart from pubspec.yaml (single source of truth: version field).
// Run from package root: dart run tool/sync_sdk_version.dart
import 'dart:io';

void main() {
  final root = Directory.current;
  final pubspecFile = File.fromUri(root.uri.resolve('pubspec.yaml'));
  if (!pubspecFile.existsSync()) {
    stderr.writeln('pubspec.yaml not found at ${pubspecFile.path}');
    exit(1);
  }
  final pubspec = pubspecFile.readAsStringSync();
  final match = RegExp(r'^version:\s*([^\s#]+)', multiLine: true).firstMatch(pubspec);
  if (match == null) {
    stderr.writeln('Could not parse version from pubspec.yaml');
    exit(1);
  }
  final version = match.group(1)!.trim();

  final outFile = File.fromUri(root.uri.resolve('lib/src/sdk_version.dart'));
  outFile.writeAsStringSync('''/// Generated by \`dart run tool/sync_sdk_version.dart\` from pubspec.yaml — do not edit by hand.
class FlittMobileSdk {
  FlittMobileSdk._();

  static const String version = ${_dartString(version)};
}
''');

  stdout.writeln('Wrote ${outFile.path} with version $version');
}

String _dartString(String s) {
  final escaped = s.replaceAll(r'\', r'\\').replaceAll("'", r"\'");
  return "'$escaped'";
}
